// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0qzfZywhsGvtHOmhvvF0dNJkhhZTfzyM',
    appId: '1:730559152401:web:1c0fee958ed4b084598cb0',
    messagingSenderId: '730559152401',
    projectId: 'jobo-fa5ed',
    authDomain: 'jobo-fa5ed.firebaseapp.com',
    storageBucket: 'jobo-fa5ed.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg5P5fHiNy2q1V_38NCpZsO3mtiXIFp58',
    appId: '1:730559152401:android:d4a9ca4de3ea0a20598cb0',
    messagingSenderId: '730559152401',
    projectId: 'jobo-fa5ed',
    storageBucket: 'jobo-fa5ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4wJvRoBQSPWn-s8uYu4A5UiWFwmgWMjw',
    appId: '1:730559152401:ios:2681e4a07898cb9a598cb0',
    messagingSenderId: '730559152401',
    projectId: 'jobo-fa5ed',
    storageBucket: 'jobo-fa5ed.appspot.com',
    androidClientId: '730559152401-e2mtve585rqj3gpasup31b6a7lduod1f.apps.googleusercontent.com',
    iosClientId: '730559152401-dhamcmgejtv4prrgft1pvpjlev6mroa1.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4wJvRoBQSPWn-s8uYu4A5UiWFwmgWMjw',
    appId: '1:730559152401:ios:2681e4a07898cb9a598cb0',
    messagingSenderId: '730559152401',
    projectId: 'jobo-fa5ed',
    storageBucket: 'jobo-fa5ed.appspot.com',
    androidClientId: '730559152401-e2mtve585rqj3gpasup31b6a7lduod1f.apps.googleusercontent.com',
    iosClientId: '730559152401-dhamcmgejtv4prrgft1pvpjlev6mroa1.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobApplication',
  );
}
